###########
# site.title

title:    'Environment->Biome'
subtitle: 'CNN Biome Recognizer for CS 175: Project in AI (in Minecraft)'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
