###########
# site.title

title:    'The Advantures of Tintin'
subtitle: 'Minecraft Biome Recognizer'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
