###########
# site.title

title:    'The Advanture of Tintin'
subtitle: 'Minecraft Biome Recognizer for CS 175: Project in AI'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
